#!/usr/bin/env bash
# =============================================================================
#  simplerec — macOS Installer
#  Supports: Intel (x86_64) and Apple Silicon (arm64)
# =============================================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
BOLD="\033[1m"; RESET="\033[0m"
GREEN="\033[32m"; YELLOW="\033[33m"; CYAN="\033[36m"; RED="\033[31m"

info()    { echo -e "${CYAN}${BOLD}[•]${RESET} $*"; }
success() { echo -e "${GREEN}${BOLD}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}${BOLD}[!]${RESET} $*"; }
error()   { echo -e "${RED}${BOLD}[✗]${RESET} $*"; exit 1; }

# ── Header ───────────────────────────────────────────────────────────────────
clear
echo -e "${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║        simplerec  —  Installer       ║"
echo "  ║   macOS CLI Audio Recorder (M4A)     ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${RESET}"
echo "  This script will install everything needed to run simplerec:"
echo "    1. Homebrew  (package manager, if not present)"
echo "    2. Python 3  (via Homebrew)"
echo "    3. ffmpeg    (audio encoding)"
echo "    4. pip packages: sounddevice, soundfile, numpy, shazamio"
echo "    5. A start script  ./simplerec-start.sh"
echo
echo -e "  ${YELLOW}Your sudo password may be required for Homebrew.${RESET}"
echo
read -r -p "  Press ENTER to continue or CTRL-C to abort …"
echo

# ── Detect architecture ───────────────────────────────────────────────────────
ARCH=$(uname -m)
if [[ "$ARCH" == "arm64" ]]; then
    BREW_PREFIX="/opt/homebrew"
    info "Detected Apple Silicon (arm64)"
else
    BREW_PREFIX="/usr/local"
    info "Detected Intel (x86_64)"
fi

# ── 1. Homebrew ───────────────────────────────────────────────────────────────
echo
info "Checking Homebrew …"
if command -v brew &>/dev/null; then
    success "Homebrew already installed at $(brew --prefix)"
else
    warn "Homebrew not found — installing now."
    echo "  Homebrew is an open-source package manager for macOS."
    echo "  It will be installed to ${BREW_PREFIX}."
    echo
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Add brew to PATH for this session
    if [[ "$ARCH" == "arm64" ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        eval "$(/usr/local/bin/brew shellenv)"
    fi
    success "Homebrew installed."
fi

# ── 2. Python 3 ───────────────────────────────────────────────────────────────
echo
info "Checking Python 3 …"
if brew list python3 &>/dev/null 2>&1 || command -v python3 &>/dev/null; then
    PY=$(command -v python3)
    PY_VER=$("$PY" --version 2>&1)
    success "Python 3 found: $PY_VER"
else
    warn "Python 3 not found — installing via Homebrew …"
    echo "  Python 3 is the runtime required by simplerec."
    brew install python3
    PY=$(command -v python3)
    success "Python 3 installed: $($PY --version)"
fi
PY=$(command -v python3)

# ── 3. ffmpeg ─────────────────────────────────────────────────────────────────
echo
info "Checking ffmpeg …"
if command -v ffmpeg &>/dev/null; then
    success "ffmpeg already installed."
else
    warn "ffmpeg not found — installing via Homebrew …"
    echo "  ffmpeg is used to encode the recorded audio into M4A (AAC) format."
    brew install ffmpeg
    success "ffmpeg installed."
fi

# ── 4. pip packages ───────────────────────────────────────────────────────────
echo
info "Installing Python packages …"
echo "  • sounddevice  — captures audio from your microphone"
echo "  • soundfile    — reads/writes audio files"
echo "  • numpy        — numerical processing for the audio stream"
echo "  • shazamio     — optional song recognition (Shazam API, async)"
echo

"$PY" -m pip install --upgrade pip --quiet
"$PY" -m pip install sounddevice soundfile numpy shazamio --upgrade --quiet
success "Python packages installed."

# ── 5. Locate main script ─────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIN_PY="$SCRIPT_DIR/simplerec.py"

if [[ ! -f "$MAIN_PY" ]]; then
    error "simplerec.py not found in $SCRIPT_DIR — please run this installer from the project folder."
fi

# ── 6. Create start script ────────────────────────────────────────────────────
echo
info "Creating start script …"

START_SCRIPT="$SCRIPT_DIR/simplerec-start.sh"

cat > "$START_SCRIPT" << STARTSCRIPT
#!/usr/bin/env bash
# simplerec — start script (auto-generated by install.sh)

# Make sure Homebrew Python is on PATH
if [[ "\$(uname -m)" == "arm64" ]]; then
    eval "\$(/opt/homebrew/bin/brew shellenv)" 2>/dev/null || true
else
    eval "\$(/usr/local/bin/brew shellenv)" 2>/dev/null || true
fi

cd "$(dirname "$MAIN_PY")"
exec python3 simplerec.py "\$@"
STARTSCRIPT

chmod +x "$START_SCRIPT"
success "Start script created: $START_SCRIPT"

# ── Done ──────────────────────────────────────────────────────────────────────
echo
echo -e "${GREEN}${BOLD}  ══════════════════════════════════════════${RESET}"
echo -e "${GREEN}${BOLD}   Installation complete!${RESET}"
echo -e "${GREEN}${BOLD}  ══════════════════════════════════════════${RESET}"
echo
echo "  To start simplerec, run:"
echo
echo -e "    ${BOLD}./simplerec-start.sh${RESET}"
echo
echo "  Options:"
echo "    ./simplerec-start.sh --help           show all options"
echo "    ./simplerec-start.sh --help-messages  explain on-screen messages"
echo
